name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-rust:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-04-25
        override: true
        profile: minimal
    - name: Test
      run: |
        cd rust/ddsaveedit
        cargo check
        cargo test
        cargo test --release
  test-java:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        java-package: jdk
    - name: Test
      run: |
        ./gradlew test
